type User {
	id: ID
	name: String
	avatar: String
	email: String
}

type UserPage {
  users: [User!]!
  hasMore: Boolean!
}

type Query {
	#users: [User]
  usersPage(startId: ID, pageSize: Int!): UserPage

}
